FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libzip-dev libpq-dev zip unzip curl git \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql pgsql

RUN pecl install xdebug && docker-php-ext-enable xdebug
COPY ./docker/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install
